# Generated by Django 5.0.4 on 2024-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_no', models.IntegerField()),
                ('city_info', models.CharField(max_length=50)),
                ('city_map', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
