# Generated by Django 5.0.4 on 2024-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_no',
            field=models.FloatField(),
        ),
    ]
